export const MONITOR_SERVICE_NAMES = [
  "Netflix",
  "Amazon Prime",
  "Disney+",
  "HBO Max",
  "Apple TV+",
  "Spotify",
  "Apple Music",
  "YouTube Music",
  "Gaana",
  "JioSaavn",
  "Google One",
  "Microsoft 365",
  "Canva",
  "Notion",
  "ChatGPT",
  "Xbox",
  "PlayStation",
  "Steam",
  "Coursera",
  "Udemy",
  "MasterClass",
] as const;

export type MonitorServiceName = (typeof MONITOR_SERVICE_NAMES)[number];

const aliasToCanonical = new Map<string, MonitorServiceName>([
  ["netflix", "Netflix"],
  ["amazon prime", "Amazon Prime"],
  ["amazon-prime", "Amazon Prime"],
  ["disney+", "Disney+"],
  ["disney plus", "Disney+"],
  ["disney-plus", "Disney+"],
  ["hbo max", "HBO Max"],
  ["hbo-max", "HBO Max"],
  ["apple tv+", "Apple TV+"],
  ["apple tv plus", "Apple TV+"],
  ["apple-tv-plus", "Apple TV+"],
  ["spotify", "Spotify"],
  ["apple music", "Apple Music"],
  ["apple-music", "Apple Music"],
  ["youtube music", "YouTube Music"],
  ["youtube-music", "YouTube Music"],
  ["gaana", "Gaana"],
  ["jiosaavn", "JioSaavn"],
  ["jio saavn", "JioSaavn"],
  ["google one", "Google One"],
  ["google-one", "Google One"],
  ["microsoft 365", "Microsoft 365"],
  ["microsoft-365", "Microsoft 365"],
  ["canva", "Canva"],
  ["canva pro", "Canva"],
  ["canva-pro", "Canva"],
  ["notion", "Notion"],
  ["notion pro", "Notion"],
  ["notion-pro", "Notion"],
  ["chatgpt", "ChatGPT"],
  ["chatgpt plus", "ChatGPT"],
  ["chatgpt-plus", "ChatGPT"],
  ["xbox", "Xbox"],
  ["xbox game pass", "Xbox"],
  ["xbox-game-pass", "Xbox"],
  ["playstation", "PlayStation"],
  ["playstation plus", "PlayStation"],
  ["playstation-plus", "PlayStation"],
  ["steam", "Steam"],
  ["steam wallet", "Steam"],
  ["steam-wallet", "Steam"],
  ["coursera", "Coursera"],
  ["coursera plus", "Coursera"],
  ["coursera-plus", "Coursera"],
  ["udemy", "Udemy"],
  ["udemy pro", "Udemy"],
  ["udemy-pro", "Udemy"],
  ["masterclass", "MasterClass"],
]);

export function normalizeMonitorServiceName(input: string): MonitorServiceName | null {
  const normalized = input.trim().toLowerCase();
  return aliasToCanonical.get(normalized) ?? null;
}

